### PR TITLE
move from OpenShiftTestAssistant to Arquillian Cube

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
I also reformatted the `pom.xml`s to use 2-space indentation (because that seems to be what the original `pom.xml` used). This clutters the diff somewhat; append `?w=1` to the URL to see the diff without whitespace changes.

**Comment by heiko-braun** [comment]
Please hold this for now. We need to decide when to make this switch

**Comment by Ladicek** [comment]
I'd argue that we actually don't, because this doesn't have any visible effect. You can still do `mvn clean verify` to run the local tests, `mvn clean verify -Popenshift,openshift-it` to run the OpenShift tests, `mvn clean fabric8:deploy -Popenshift` to deploy to OpenShift via FMP, etc. I'd also argue that we don't necessarily have to switch all the boosters at once, though it would of course be nice :-)

But if you have any concerns, I'm of course open to discussin them.

**Comment by Ladicek** [comment]
Actually yes, please hold this, because I found an issue. After the test, pods keep hanging in the "Terminating" state, which is super bad.

**Comment by heiko-braun** [comment]
It may not have an impact from the user point of view, but technically speaking there are a number of issues that concern me:

- What does it mean for productised boosters to introduce a set of new dependencies?
- What's the level of uncertainty with using a new technology? 
- Are there any risks involved? I.e. can it break in certain environments?
- What's the argument for doing it now, rather then after GA?

**Comment by Ladicek** [comment]
Let's discuss this via e-mail, I want everyone to be involved. I'll send an e-mail to the list.

**Comment by Ladicek** [comment]
Rebased and added back the awaiting of the route to return 200.

**Comment by Ladicek** [comment]
Updated to Arquillian Cube 1.9.1.

**Pull request merged**
